version: '3'

services:
   db:
     image: webhippie/mariadb:latest
     ports:
      - '3306:3306'
     volumes:
       - db-data:/var/lib/mysql
     environment:
       MARIADB_ROOT_PASSWORD: roothahah
       MARIADB_DATABASE: wordpress
       MARIADB_USERNAME: wordpress
       MARIADB_PASSWORD: wordpress
   minio:
     image: minio/minio:latest
     ports:
       - '9000:9000'
     volumes:
       - minio-buckets:/var/lib/minio/buckets
     environment:
       MINIO_ACCESS_KEY: minio
       MINIO_SECRET_KEY: minio123
     command: server /var/lib/minio/buckets
   minio-setup:
     image: minio/mc:latest
     depends_on:
       - minio
     entrypoint: sh /root/run-mc.sh
     volumes:
       - minio-mc:/root/.mc
       - ./docker/run-mc.sh:/root/run-mc.sh
   minio-client:
     image: minio/mc:latest
     volumes:
       - minio-mc:/root/.mc
   php:
     depends_on:
       - db
       - minio
     build: ./docker/php-fpm
     volumes:
       - ./:/var/www/html
       - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
     environment:
       # you can set this in the .env file. Example value: 
       # XDEBUG_CONFIG='idekey=xxx remote_host=10.0.0.242 remote_port=9000'
       XDEBUG_CONFIG: "${XDEBUG_CONFIG}"
   web:
     depends_on:
       - php
     image: nginx:mainline-alpine
     ports:
       - '80:80'
     volumes:
       - ./:/var/www/html
       - ./docker/site-nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  db-data:
  minio-buckets:
  minio-mc:
